base:
  font-color: #333333
  line-height-length: 20
  line-height: $base-line-height-length / $base-font-size
heading:
  font-color: #FF8000
  font-size: 12
  font-style: bold
  line-height: 1.2
link:
  font-color: #009900
