# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Lscripts Docker
description: >- # this means to ignore newlines until "baseurl:"
  Develop a perspective of what happens when shell scripts limits are pushed to be used in conjunction with machine learning and deep learning projects. When the shell scripts and the command line tools are combined with python it provide for the powerful triad for a cadence.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.skillplot.org" # the base hostname & protocol for your site, e.g. http://example.com
email: skillplot@gmail.com
twitter_username: theskillplot
github_username:  skillplot

# Authors
authors:
  mangal:
    name: mangalbhaskar
    display_name: Mangal
    # gravatar: 
    email: skillplot@gmail.com
    web: http://www.skillplot.org
    twitter: https://twitter.com/theskillplot
    description: "Author of Skillplot."


# Build settings
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

words_per_minute: 200

# Pagination 
paginate: 5 # amount of posts to show
paginate_path: /page:num/
# paginate_path: /blog/page:num/
timezone: Asia/Kolkata # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


include:
  - .htaccess
  - _pages
  - _posts

exclude: 
  - node_modules
  - changelog.md
  - LICENSE.txt
  - README.md
  - CREDITS.md
  - Gemfile
  - Gemfile.lock
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
